import { MatrixModule } from "@/interface";

export const MATRIX_MODULES: MatrixModule[] = [
  {
    id: "dashboard",
    name: "Dashboard",
    slug: "dashboards",
    avatarChar: "D",
    avatarBg: "bg-blue-600",
    viewKey: "dashboard.view",
    addKey: "dashboard.create",
    updateKey: "dashboard.edit",
    deleteKey: "dashboard.delete",
  },
  {
    id: "organization",
    name: "Organization",
    slug: "organization",
    avatarChar: "O",
    avatarBg: "bg-purple-600",
    viewKey: "organizations.view",
    addKey: "organizations.create",
    updateKey: "organizations.edit",
    deleteKey: "organizations.delete",
  },
  {
    id: "users",
    name: "Users",
    slug: "users",
    avatarChar: "U",
    avatarBg: "bg-sky-500",
    viewKey: "settings.users.view",
    addKey: "settings.users.create",
    updateKey: "settings.users.edit",
    deleteKey: "settings.users.delete",
  },
  {
    id: "roles",
    name: "Roles",
    slug: "roles",
    avatarChar: "R",
    avatarBg: "bg-emerald-600",
    viewKey: "settings.roles.view",
    addKey: "settings.roles.create",
    updateKey: "settings.roles.edit",
    deleteKey: "settings.roles.delete",
  },
  {
    id: "user_access",
    name: "User Access Manage",
    slug: "access-management",
    avatarChar: "U",
    avatarBg: "bg-amber-500",
    viewKey: "settings.access_management.view",
    addKey: "settings.access_management.create",
    updateKey: "settings.access_management.edit",
    deleteKey: "settings.access_management.delete",
  },
  {
    id: "groups",
    name: "Groups",
    slug: "groups",
    avatarChar: "G",
    avatarBg: "bg-indigo-600",
    viewKey: "settings.groups.view",
    addKey: "settings.groups.create",
    updateKey: "settings.groups.edit",
    deleteKey: "settings.groups.delete",
  },
  {
    id: "leads",
    name: "Leads",
    slug: "leads",
    avatarChar: "L",
    avatarBg: "bg-cyan-600",
    viewKey: "leads.view",
    addKey: "leads.create",
    updateKey: "leads.edit",
    deleteKey: "leads.delete",
  },
  {
    id: "quotes",
    name: "Quotes",
    slug: "quotes",
    avatarChar: "Q",
    avatarBg: "bg-violet-600",
    viewKey: "quotes.view",
    addKey: "quotes.create",
    updateKey: "quotes.edit",
    deleteKey: "quotes.delete",
  },
  {
    id: "mail",
    name: "Mail",
    slug: "mail",
    avatarChar: "M",
    avatarBg: "bg-blue-500",
    viewKey: "mail.inbox",
    addKey: "mail.draft",
    updateKey: "mail.setting",
    deleteKey: "mail.trash",
  },
  {
    id: "activities",
    name: "Activities",
    slug: "activities",
    avatarChar: "A",
    avatarBg: "bg-orange-500",
    viewKey: "activities.view",
    addKey: "activities.create",
    updateKey: "activities.edit",
    deleteKey: "activities.delete",
  },
  {
    id: "persons",
    name: "Persons",
    slug: "persons",
    avatarChar: "P",
    avatarBg: "bg-pink-600",
    viewKey: "contacts.persons.view",
    addKey: "contacts.persons.create",
    updateKey: "contacts.persons.edit",
    deleteKey: "contacts.persons.delete",
  },
  {
    id: "products",
    name: "Products",
    slug: "products",
    avatarChar: "P",
    avatarBg: "bg-teal-600",
    viewKey: "products.view",
    addKey: "products.create",
    updateKey: "products.edit",
    deleteKey: "products.delete",
  },
  {
    id: "pipelines",
    name: "Pipelines",
    slug: "pipelines",
    avatarChar: "P",
    avatarBg: "bg-emerald-500",
    viewKey: "settings.pipelines.view",
    addKey: "settings.pipelines.create",
    updateKey: "settings.pipelines.edit",
    deleteKey: "settings.pipelines.delete",
  },
  {
    id: "sources",
    name: "Sources",
    slug: "sources",
    avatarChar: "S",
    avatarBg: "bg-indigo-500",
    viewKey: "settings.sources.view",
    addKey: "settings.sources.create",
    updateKey: "settings.sources.edit",
    deleteKey: "settings.sources.delete",
  },
  {
    id: "types",
    name: "Types",
    slug: "types",
    avatarChar: "T",
    avatarBg: "bg-purple-500",
    viewKey: "settings.types.view",
    addKey: "settings.types.create",
    updateKey: "settings.types.edit",
    deleteKey: "settings.types.delete",
  },
  {
    id: "warehouses",
    name: "Warehouses",
    slug: "warehouses",
    avatarChar: "W",
    avatarBg: "bg-[#0088cc]",
    viewKey: "settings.warehouses.view",
    addKey: "settings.warehouses.create",
    updateKey: "settings.warehouses.edit",
    deleteKey: "settings.warehouses.delete",
  },
  {
    id: "attributes",
    name: "Attributes",
    slug: "attributes",
    avatarChar: "A",
    avatarBg: "bg-slate-700",
    viewKey: "settings.attributes.view",
    addKey: "settings.attributes.create",
    updateKey: "settings.attributes.edit",
    deleteKey: "settings.attributes.delete",
  },
  {
    id: "email_templates",
    name: "Email Templates",
    slug: "email-templates",
    avatarChar: "E",
    avatarBg: "bg-green-600",
    viewKey: "settings.email_templates.view",
    addKey: "settings.email_templates.create",
    updateKey: "settings.email_templates.edit",
    deleteKey: "settings.email_templates.delete",
  },
  {
    id: "events",
    name: "Events",
    slug: "events",
    avatarChar: "E",
    avatarBg: "bg-rose-600",
    viewKey: "settings.events.view",
    addKey: "settings.events.create",
    updateKey: "settings.events.edit",
    deleteKey: "settings.events.delete",
  },
  {
    id: "campaigns",
    name: "Campaigns",
    slug: "campaigns",
    avatarChar: "C",
    avatarBg: "bg-sky-600",
    viewKey: "settings.campaigns.view",
    addKey: "settings.campaigns.create",
    updateKey: "settings.campaigns.edit",
    deleteKey: "settings.campaigns.delete",
  },
  {
    id: "webhooks",
    name: "Webhooks",
    slug: "webhooks",
    avatarChar: "W",
    avatarBg: "bg-amber-600",
    viewKey: "settings.webhooks.view",
    addKey: "settings.webhooks.create",
    updateKey: "settings.webhooks.edit",
    deleteKey: "settings.webhooks.delete",
  },
  {
    id: "workflows",
    name: "Workflows",
    slug: "workflows",
    avatarChar: "W",
    avatarBg: "bg-blue-600",
    viewKey: "settings.workflows.view",
    addKey: "settings.workflows.create",
    updateKey: "settings.workflows.edit",
    deleteKey: "settings.workflows.delete",
  },
  {
    id: "webforms",
    name: "Web Forms",
    slug: "web-forms",
    avatarChar: "W",
    avatarBg: "bg-indigo-600",
    viewKey: "settings.webforms.view",
    addKey: "settings.webforms.create",
    updateKey: "settings.webforms.edit",
    deleteKey: "settings.webforms.delete",
  },
  {
    id: "tags",
    name: "Tags",
    slug: "tags",
    avatarChar: "T",
    avatarBg: "bg-teal-500",
    viewKey: "settings.tags.view",
    addKey: "settings.tags.create",
    updateKey: "settings.tags.edit",
    deleteKey: "settings.tags.delete",
  },
  {
    id: "data_transfer",
    name: "Data Transfer",
    slug: "data-transfer",
    avatarChar: "D",
    avatarBg: "bg-stone-600",
    viewKey: "settings.data_transfer.view",
    addKey: "settings.data_transfer.create",
    updateKey: "settings.data_transfer.edit",
    deleteKey: "settings.data_transfer.delete",
  },
  {
    id: "google_contacts",
    name: "Google Contacts",
    slug: "google-contacts",
    avatarChar: "G",
    avatarBg: "bg-red-500",
    viewKey: "settings.google_contacts.view",
    addKey: "settings.google_contacts.create",
    updateKey: "settings.google_contacts.edit",
    deleteKey: "settings.google_contacts.delete",
  },
  {
    id: "configuration",
    name: "Configuration",
    slug: "configuration",
    avatarChar: "C",
    avatarBg: "bg-slate-600",
    viewKey: "settings.configuration.view",
    addKey: "settings.configuration.create",
    updateKey: "settings.configuration.edit",
    deleteKey: "settings.configuration.delete",
  },
];
